In [1]:
import numpy as np

In [2]:
def arnoldi_iteration(A, b, n: int):
    """Compute a basis of the (n + 1)-Krylov subspace of the matrix A.

    This is the space spanned by the vectors {b, Ab, ..., A^n b}.

    Parameters
    ----------
    A : array_like
        An m × m array.
    b : array_like
        Initial vector (length m).
    n : int
        One less than the dimension of the Krylov subspace, or equivalently the *degree* of the Krylov space. Must be >= 1.
    
    Returns
    -------
    Q : numpy.array
        An m x (n + 1) array, where the columns are an orthonormal basis of the Krylov subspace.
    h : numpy.array
        An (n + 1) x n array. A on basis Q. It is upper Hessenberg.
    """
    eps = 1e-12
    h = np.zeros((n + 1, n))
    Q = np.zeros((A.shape[0], n + 1))
    # Normalize the input vector
    Q[:, 0] = b / np.linalg.norm(b, 2)  # Use it as the first Krylov vector
    for k in range(1, n + 1):
        v = np.dot(A, Q[:, k - 1])  # Generate a new candidate vector
        for j in range(k):  # Subtract the projections on previous vectors
            h[j, k - 1] = np.dot(Q[:, j].conj(), v)
            v = v - h[j, k - 1] * Q[:, j]
        h[k, k - 1] = np.linalg.norm(v, 2)
        if h[k, k - 1] > eps:  # Add the produced vector to the list, unless
            Q[:, k] = v / h[k, k - 1]
        else:  # If that happens, stop iterating.
            return Q, h
    return Q, h

In [ ]:

def hessenberg_matrix(A) :
    b = A[:,0]
    n = np.shape(A)[0]
    Q, h = arnoldi_iteration(A, b, n)
    hnn = np.delete(h, -1, 0)
    return hnn

In [ ]:
# QR algorithm

def QR_algorithm(A, m) :
    """
    A : matrix
    n : # of iteration for arnoldi iteration
    m : # of iteration for QR algorithm
    
    """

    hnn = hessenberg_matrix(A)
    for i in range(m) :
        q, r = np.linalg.qr(hnn)
        hnn = np.dot(r,q)
    
    eigen_value, eigen_vectors = np.linalg.eig(hnn)

    return eigen_value, eigen_vectors
    
    

        


In [4]:
# construct matrix
A = np.arange(36).reshape((6,6))

In [5]:
A

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [6]:
b = np.array([1,1,1,1,1,1])

In [12]:
Q, h = arnoldi_iteration(A, b, 6)

In [13]:
h.shape

(7, 6)

In [16]:
hnn = np.delete(h,6,0)

In [19]:
q, r = np.linalg.qr(hnn)

In [20]:
np.dot(r,q)

array([[ 1.09468085e+02, -5.38509966e+01,  3.95014996e-14,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-2.61624275e+00, -4.46808511e+00,  3.27748924e-15,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00]])

In [22]:
#QR method
for i in range(20) :
    q, r = np.linalg.qr(hnn)
    hnn = np.dot(r,q)


In [23]:
hnn

array([[ 1.10691494e+02,  5.12347538e+01, -3.94168695e-14,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-8.66486405e-25, -5.69149422e+00,  4.17382361e-15,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00]])

In [24]:
np.linalg.eig(hnn)

(array([110.69149422,  -5.69149422,   0.        ,   0.        ,
          0.        ,   0.        ]),
 array([[ 1.00000000e+00, -4.02911482e-01,  1.66604129e-17,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00,  9.15238951e-01,  7.33344082e-16,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  1.00000000e+00]]))