In [2]:
import numpy as np
import itertools as it

In [3]:
# num of states of mRNA
mN = 10
# num of states of protein
pN = 10
#num of states
N = mN*pN

In [4]:
# states for mRNA and protein
s = []
for i in range(mN) :
    for j in range(pN) :
        s.append(np.array([i,j]))

s = np.array(s)


In [5]:
# average of mRNA
avg_m = 5
# average of protein 
avg_p = 12

In [6]:
# production coefficient of mRNA
alpha = 5
# production coefficient of protein
betta = avg_p/avg_m
# degradation coefficient of mRNA
gamma = alpha/avg_m
# degradation coefficient of protein
delta = 1 # unit value

In [7]:
print(alpha,betta,gamma,delta)

5 2.4 1.0 1


In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
# # Stochastic matrix
# M = np.zeros((N,N))

# I = np.eye()

# for i in range(N) :
#     for j in range(N) :
#         # Diagonal comonent
#         if i == j :
#             M[i, j] = alpha + s[i,0]*betta + s[i,0]*gamma + s[i,1]*delta
        
#         # off-diagonal component

#         # degradation of mRNA(m+1 -> m)
#         elif  s[i,0] - s[j,0] == -1 :
#             if abs(s[i,1] - s[j,1]) != 0 :
#                 break
#             M[i,j] = M[i,j] - s[j,0]*gamma
#         # production of mRNA(m-1 =>m)
#         elif s[i,0] + s[j,0] == 1 :
#             if abs(s[i,1] - s[j,1]) != 0 :
#                 break
#             M[i,j] = M[i,j] - alpha
#         # degradation of protein(p+1 -> p)
#         elif  s[i,1] - s[j,1] == -1 :
#             if abs(s[i,0] - s[j,0]) != 0 :
#                 break
#             M[i,j] = M[i,j] - s[j,1]*delta
#         # degradation of protein(p-1 -> p)
#         elif  s[i,1] - s[j,1] == 1 :
#             if abs(s[i,0] - s[j,0]) != 0 :
#                 break
#             M[i,j] = M[i,j] - s[j,0]*betta



In [19]:
# Stochastic matrix
M = np.zeros((N,N))

Im = np.eye(mN+1)
Ip = np.eye(pN+1)

for i in range(N) :
    for j in range(N) :

        M[i,j] = alpha*(Im[s[i,0],s[j,0]]*Ip[s[i,1],s[j,1]] - Im[s[i,0]-1,s[j,0]]*Ip[s[i,1],s[j,1]])
        M[i,j] = M[i,j] + betta*s[j,0]*(Im[s[i,0],s[j,0]]*Ip[s[i,1],s[j,1]] - Im[s[i,0],s[j,0]]*Ip[s[i,1]-1,s[j,1]])
        M[i,j] = M[i,j] + gamma*(s[i,0]*Im[s[i,0],s[j,0]]*Ip[s[i,1],s[j,1]] - s[j,0]*Im[s[i,0]+1,s[j,0]]*Ip[s[i,1],s[j,1]])
        M[i,j] = M[i,j] + delta*(s[i,1]*Im[s[i,0],s[j,0]]*Ip[s[i,1],s[j,1]] - s[j,1]*Im[s[i,0],s[j,0]]*Ip[s[i,1]+1,s[j,1]])

#normalization
for i in range(N) :
    M[i,i] = M[i,i] - np.sum(M[:,i])

In [20]:
M

array([[  5. ,  -1. ,   0. , ...,   0. ,   0. ,   0. ],
       [  0. ,   6. ,  -2. , ...,   0. ,   0. ,   0. ],
       [  0. ,   0. ,   7. , ...,   0. ,   0. ,   0. ],
       ...,
       [  0. ,   0. ,   0. , ...,  42.6,  -8. ,   0. ],
       [  0. ,   0. ,   0. , ..., -21.6,  43.6,  -9. ],
       [  0. ,   0. ,   0. , ...,   0. , -21.6,  44.6]])

In [21]:
np.sum(M)

158.0

In [22]:
np.sum(M, axis = 0)

array([ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00, -1.77635684e-15,  2.40000000e+00,
        8.88178420e-16,  8.88178420e-16,  8.88178420e-16,  8.88178420e-16,
        8.88178420e-16,  8.88178420e-16,  8.88178420e-16,  8.88178420e-16,
        8.88178420e-16,  4.80000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  7.20000000e+00,
        1.77635684e-15,  1.77635684e-15,  1.77635684e-15,  1.77635684e-15,
        1.77635684e-15,  1.77635684e-15,  1.77635684e-15,  1.77635684e-15,
        1.77635684e-15,  9.60000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  