In [5]:
import numpy as np
import itertools as it

In [6]:
# num of states of mRNA
mN = 10
# num of states of protein
pN = 10
#num of states
N = mN*pN

In [7]:
# states for mRNA and protein
s = []
for i in range(mN) :
    for j in range(pN) :
        s.append(np.array([i,j]))

s = np.array(s)


In [8]:
# average of mRNA
avg_m = 5
# average of protein 
avg_p = 12

In [9]:
# production coefficient of mRNA
alpha = 5
# production coefficient of protein
betta = avg_p/avg_m
# degradation coefficient of mRNA
gamma = alpha/avg_m
# degradation coefficient of protein
delta = 1 # unit value

In [10]:
print(alpha,betta,gamma,delta)

5 2.4 1.0 1


In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
# # Stochastic matrix
# M = np.zeros((N,N))

# I = np.eye()

# for i in range(N) :
#     for j in range(N) :
#         # Diagonal comonent
#         if i == j :
#             M[i, j] = alpha + s[i,0]*betta + s[i,0]*gamma + s[i,1]*delta
        
#         # off-diagonal component

#         # degradation of mRNA(m+1 -> m)
#         elif  s[i,0] - s[j,0] == -1 :
#             if abs(s[i,1] - s[j,1]) != 0 :
#                 break
#             M[i,j] = M[i,j] - s[j,0]*gamma
#         # production of mRNA(m-1 =>m)
#         elif s[i,0] + s[j,0] == 1 :
#             if abs(s[i,1] - s[j,1]) != 0 :
#                 break
#             M[i,j] = M[i,j] - alpha
#         # degradation of protein(p+1 -> p)
#         elif  s[i,1] - s[j,1] == -1 :
#             if abs(s[i,0] - s[j,0]) != 0 :
#                 break
#             M[i,j] = M[i,j] - s[j,1]*delta
#         # degradation of protein(p-1 -> p)
#         elif  s[i,1] - s[j,1] == 1 :
#             if abs(s[i,0] - s[j,0]) != 0 :
#                 break
#             M[i,j] = M[i,j] - s[j,0]*betta



In [13]:
# Stochastic matrix
M = np.zeros((N,N))

Im = np.eye(mN+1)
Ip = np.eye(pN+1)

for i in range(N) :
    for j in range(N) :

        M[i,j] = alpha*(Im[s[i,0],s[j,0]]*Ip[s[i,1],s[j,1]] - Im[s[i,0]-1,s[j,0]]*Ip[s[i,1],s[j,1]])
        M[i,j] = M[i,j] + betta*s[j,0]*(Im[s[i,0],s[j,0]]*Ip[s[i,1],s[j,1]] - Im[s[i,0],s[j,0]]*Ip[s[i,1]-1,s[j,1]])
        M[i,j] = M[i,j] + gamma*(s[i,0]*Im[s[i,0],s[j,0]]*Ip[s[i,1],s[j,1]] - s[j,0]*Im[s[i,0]+1,s[j,0]]*Ip[s[i,1],s[j,1]])
        M[i,j] = M[i,j] + delta*(s[i,1]*Im[s[i,0],s[j,0]]*Ip[s[i,1],s[j,1]] - s[j,1]*Im[s[i,0],s[j,0]]*Ip[s[i,1]+1,s[j,1]])

#normalization
for i in range(N) :
    M[i,i] = M[i,i] - np.sum(M[:,i])

In [20]:
M

array([[  5. ,  -1. ,   0. , ...,   0. ,   0. ,   0. ],
       [  0. ,   6. ,  -2. , ...,   0. ,   0. ,   0. ],
       [  0. ,   0. ,   7. , ...,   0. ,   0. ,   0. ],
       ...,
       [  0. ,   0. ,   0. , ...,  42.6,  -8. ,   0. ],
       [  0. ,   0. ,   0. , ..., -21.6,  43.6,  -9. ],
       [  0. ,   0. ,   0. , ...,   0. , -21.6,  44.6]])

In [1]:
pip install import_ipynb

Note: you may need to restart the kernel to use updated packages.


In [3]:
import import_ipynb
import arnoldi

importing Jupyter notebook from arnoldi.ipynb


In [14]:
arnoldi.QR_algorithm(M,100)

(array([ 6.78459210e+01+0.j        ,  6.03455702e+01+0.j        ,
         5.93584712e+01+0.j        ,  5.44266924e+01+0.j        ,
         5.27291862e+01+0.24678261j,  5.27291862e+01-0.24678261j,
         4.92098366e+01+0.j        ,  4.83507849e+01+0.j        ,
         4.65060928e+01+0.67144806j,  4.65060928e+01-0.67144806j,
         4.44826214e+01+0.j        ,  4.36213842e+01+0.j        ,
         4.18287127e+01+0.j        ,  4.12718969e+01+0.88763961j,
         4.12718969e+01-0.88763961j,  4.01019088e+01+0.j        ,
         3.85152235e+01+0.j        ,  3.72830105e+01+0.20264841j,
         3.72830105e+01-0.20264841j,  3.64356039e+01+1.07968549j,
         3.64356039e+01-1.07968549j,  3.59731976e+01+0.j        ,
         3.30099645e+01+0.25011046j,  3.30099645e+01-0.25011046j,
         3.28545442e+01+0.71390155j,  3.28545442e+01-0.71390155j,
         3.20173128e+01+1.24702333j,  3.20173128e+01-1.24702333j,
         3.20080513e+01+0.j        ,  2.89746669e+01+0.j        ,
         2

In [15]:
arnoldi.QR_algorithm(M,200)

(array([ 6.78459210e+01+0.j        ,  6.03455702e+01+0.j        ,
         5.93584712e+01+0.j        ,  5.44266924e+01+0.j        ,
         5.27291862e+01+0.24678261j,  5.27291862e+01-0.24678261j,
         4.92098366e+01+0.j        ,  4.83507849e+01+0.j        ,
         4.65060928e+01+0.67144806j,  4.65060928e+01-0.67144806j,
         4.44826214e+01+0.j        ,  4.36213842e+01+0.j        ,
         4.18287127e+01+0.j        ,  4.12718969e+01+0.88763961j,
         4.12718969e+01-0.88763961j,  4.01019088e+01+0.j        ,
         3.85152235e+01+0.j        ,  3.72830105e+01+0.20264841j,
         3.72830105e+01-0.20264841j,  3.64356039e+01+1.07968549j,
         3.64356039e+01-1.07968549j,  3.59731976e+01+0.j        ,
         3.30099645e+01+0.25011046j,  3.30099645e+01-0.25011046j,
         3.28545442e+01+0.71390155j,  3.28545442e+01-0.71390155j,
         3.20173128e+01+1.24702333j,  3.20173128e+01-1.24702333j,
         3.20080513e+01+0.j        ,  2.89746669e+01+0.j        ,
         2